  adapter: postgresql
  encoding: unicode

  database: globalstripe

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: globalstripe

  # The password associated with the postgres role (username).
  password: 5B57E9F2-A7E9-46DA-B1D2-448334CC6233

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: globalstripedb.demo.cockroachdb.dev

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 26257

  sslmode: require
